server:
  port: 9000

logging:
  level:
    root: info

#logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

#jsp 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

#database 설정
  datasource:
    url: jdbc:mariadb://localhost:3306/practice
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver

# MyBatis 설정
mybatis:
#    sql file location
#    classpath : src/resources
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.spring.mvcproject.database.mybatis
  configuration:
    map-underscore-to-camel-case: true